### ISSUE TITLE
QR Code printed on head - ZPL

### ISSUE THREAD

**Issue by cdiethelm** [luis901101/zsdk#8]
The printout will turn out with the top side on the bottom. 
That itself wouldnt be a problem but the qr code will turn out on the right side and is on its head. 

Unfortunately, there is no way in ZPL to turn the QR Code to the right side. 

I have attached an image.
![IMG_0126](https://user-images.githubusercontent.com/46853231/178943592-7f3be6f4-9808-4140-b54b-3ef44aaec74b.jpg)
 
Here is my ZPL
```
^XA~TA000~JSN^LT0^MNW^MTT^PON^PMN^LH0,0^JMA^PR4,4~SD15^JUS^LRN^CI0^XZ
^XA
^MMT
^PW1205
^LL0449
^LS0
^FT1171,233^A0I,46,45^FH\^FDITEM-2021-00001^FS
^FO945,173^GB226,0,3^FS
^FT1171,27^A0I,54,52^FH\^FD675-L00-E2E-900x2000-S-1150x1400x2150-^FS
^FT1171,95^A0I,54,52^FH\^FD675-L00-E2E-900x2000-S-1150x1400x2150-^FS
^FT37,446^BQN,2,9
^FH\^FDHA,ITEM-2020-02222^FS
^PQ1,0,1,Y^XZ
```

**Comment by cdiethelm** [comment]
Tested on a ZD421 - which otherwise runs perfectly

**Comment by luis901101** [comment]
this doesn't not seem a problem related to the plugin.
